/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package login_s;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnRoom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnMeals = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbtnRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbtnDisplay = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 153));

        jPanel1.setForeground(new java.awt.Color(255, 51, 204));
        jPanel1.setLayout(null);

        jbtnRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/single.jpg"))); // NOI18N
        jbtnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRoomActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRoom);
        jbtnRoom.setBounds(10, 490, 300, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ima.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 460);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/meals table.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(670, 0, 930, 460);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Rooms");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 630, 70, 30);

        jbtnMeals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon1.jpg"))); // NOI18N
        jbtnMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMealsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMeals);
        jbtnMeals.setBounds(380, 490, 280, 140);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Meals");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 640, 60, 22);

        jbtnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registe1.jpg"))); // NOI18N
        jbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegister);
        jbtnRegister.setBounds(720, 490, 300, 140);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Register");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(860, 640, 80, 22);

        jbtnDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/display.png"))); // NOI18N
        jbtnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDisplay);
        jbtnDisplay.setBounds(1060, 490, 230, 140);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Display");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1140, 640, 70, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRoomActionPerformed
        Rooms obj=new Rooms();
        obj.show();
    }//GEN-LAST:event_jbtnRoomActionPerformed

    private void jbtnMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMealsActionPerformed
        Meals obj=new Meals();
        obj.show();
    }//GEN-LAST:event_jbtnMealsActionPerformed

    private void jbtnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDisplayActionPerformed
        // TODO add your handling code here:
        Display obj=new Display();
        obj.show();
    }//GEN-LAST:event_jbtnDisplayActionPerformed

    private void jbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegisterActionPerformed
        // TODO add your handling code here:
        Register obj=new Register();
        obj.show();
    }//GEN-LAST:event_jbtnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDisplay;
    private javax.swing.JButton jbtnMeals;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JButton jbtnRoom;
    // End of variables declaration//GEN-END:variables
}
